### PR TITLE
🐦 v11 tweet

### PR DESCRIPTION
**Pull request by gr2m**
We should update the release notes before posting. 

@paulmelnikow @mastermatt

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Release notes might take a few days. Worth tweeting something in the interim?

We could say we've got a stable release and we're working on the upgrade guide.

**Comment by gr2m** [comment]
I'd wait until the release notes are ready, it will make it more likely for people to test the new release

**Comment by gr2m** [comment]
Oops I guess that one is obsolete now :) Let me update it

**Comment by gr2m** [comment]
ping @paulmelnikow, @RichardLitt, @mastermatt

**Review by paulmelnikow — APPROVED** [review]
🎉🎉🎉

**Review by mastermatt — APPROVED** [review]
Almost makes me want to create a Twitter account...almost.

**Comment by gr2m** [comment]
lets tweet it tomorrow morning (LA time).

**Comment by RichardLitt** [comment]
🎉 Woo.

**Pull request merged**
